## 框架的核心配置项和菜单结构。 业务项目需在 application-data.yml 中进行配置。
data:
  dicts:
    - label: 机构类型
      code: orgType
      items:
        - {label: 单位, code: 10, color: success}
        - {label: 部门, code: 20}
    - label: 审核状态
      code: approveStatus
      items:
        - {label: 待提交, code: DRAFT, color: default}
        - {label: 审核中, code: PENDING, color: warning}
        - {label: 审核通过, code: APPROVED, color: success}
        - {label: 审核未通过, code: REJECTED, color: error}
    - label: 性别
      code: sex
      items:
        - {label: 男, code: MALE}
        - {label: 女, code: FEMALE}
        - {label: 保密, code: UNKNOWN}
    - label: 是否
      code: yesNo
      items:
        - {label: 是, code: Y, color: success}
        - {label: 否, code: N, color: error}
    - label: 数据权限
      code: dataPermType
      items:
        - {label: 所有, code: ALL}
        - {label: 本级, code: LEVEL}
        - {label: 本级和子级, code: CHILDREN}
        - {label: 自定义, code: CUSTOM}
    - label: 状态颜色
      code: statusColor
      items:
        - {label: 成功, code: SUCCESS}
        - {label: 处理中, code: PROCESSING}
        - {label: 错误, code: ERROR}
        - {label: 警告, code: WARNING}
        - {label: 默认, code: DEFAULT}
        - {label: 红色, code: RED}
        - {label: 蓝色, code: BLUE}
        - {label: 绿色, code: GREEN}
        - {label: 灰色, code: GRAY}

  menus:
    - id: sys
      name: 系统管理
      seq: 10000
      icon: SettingOutlined
      children:
        - id: sys-user
          name: 用户管理
          path: /system/user
          icon: UserOutlined
          perms:
            - {name: 查询, code: query}
            - {name: 新增, code: save}
            - {name: 删除, code: delete}
            - {name: 重置密码, code: reset-password}
            - {name: 分配权限, code: grant-permission}
        - id: sys-org
          name: 机构管理
          path: /system/org
          icon: ApartmentOutlined
          perms:
            - {name: 查询, code: query}
            - {name: 新增, code: save}
            - {name: 删除, code: delete}
        - id: sys-role
          name: 角色管理
          path: /system/role
          icon: IdcardOutlined
          perms:
            - {name: 查询, code: query}
            - {name: 新增, code: save}
            - {name: 删除, code: delete}
            - {name: 分配权限, code: grant-permission}
        - id: sys-manual
          name: 操作手册
          path: /system/manual
          icon: CopyOutlined
          perms:
            - {name: 查看, code: query}
            - {name: 新增, code: save}
            - {name: 删除, code: delete}
        - id: sys-dict
          name: 数据字典
          path: /system/dict
          icon: FileSearchOutlined
          perms:
            - {name: 查询, code: query}
            - {name: 新增, code: save}
            - {name: 删除, code: delete}
        - id: job
          name: 定时作业
          path: /system/job
          icon: OrderedListOutlined
          perms:
            - {name: 查询, code: query}
            - {name: 新增, code: save}
            - {name: 删除, code: delete}
            - {name: 执行一次, code: trigger}
            - {name: 清理日志, code: clean-log}
        - id: sys-file
          name: 文件管理
          path: /system/file
          icon: FolderOpenOutlined
          perms:
            - {name: 查看, code: query}
            - {name: 删除, code: delete}
        - id: api
          name: 接口管理
          icon: ApiOutlined
          path: /system/api
          perms:
            - {name: 查询, code: query}
            - {name: 新增, code: save}
            - {name: 删除, code: delete}
        - id: sys-log
          name: 操作日志
          path: /system/log
          icon: FileSearchOutlined
          perms:
            - {name: 查看, code: query}
