server:
  servlet:
    context-path: /change-this-servlet-context  # TODO 业务项目按需调整

spring:
  config:
    import: classpath:application-lib.yml

sys:
  captcha-enable: false

db_ip: 127.0.0.1
db_port: 3306
db_database: open-admin
db_username: root
db_password: 123456


